### ISSUE TITLE
Renaming files with Python 3 not working

### ISSUE THREAD

**Issue by Jeffguitarhero** [arturolszak/parampl#6]
I try to run the code with python 3 but I have this error:

Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #1 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #2 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #3 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #4 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #5 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #6 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #7 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #8 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #9 in 0.1 sec... 
Traceback (most recent call last):
  File "parampl.py", line 639, in <module>
    jobNumber = parampl.submit(queueId)
  File "parampl.py", line 202, in submit
    self.renameFile(self.problemfile(queueId) + "." + PARAMPL_NL_FILE_EXT, PARAMPL_JOB_PROBLEM_FILE_PREFIX + "_" + queueId + "_" + str(jobNumber) + "." + PARAMPL_NL_FILE_EXT)
  File "parampl.py", line 497, in renameFile
    os.rename(old, new)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'parampl_problem_powelltest.nl' -> 'parampl_job_powelltest_1.nl'
exit code 1
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #1 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #2 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #3 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #4 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #5 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #6 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #7 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #8 in 0.1 sec... 
Error renaming file: parampl_problem_powelltest.nl to: parampl_job_powelltest_1.nl. Retrying #9 in 0.1 sec... 
Traceback (most recent call last):
  File "parampl.py", line 639, in <module>
    jobNumber = parampl.submit(queueId)
  File "parampl.py", line 202, in submit
    self.renameFile(self.problemfile(queueId) + "." + PARAMPL_NL_FILE_EXT, PARAMPL_JOB_PROBLEM_FILE_PREFIX + "_" + queueId + "_" + str(jobNumber) + "." + PARAMPL_NL_FILE_EXT)
  File "parampl.py", line 497, in renameFile
    os.rename(old, new)
FileExistsError: [WinError 183] No se puede crear un archivo que ya existe: 'parampl_problem_powelltest.nl' -> 'parampl_job_powelltest_1.nl'
exit code 1
Error at _cmdno 51 executing "write" command
error processing objective obj:
	invalid subscript p1[3]
<<< Process finished. (Exit code 2)

**Comment by arturolszak** [comment]
Hello,

Thank you for reporting an issue with Parampl. Ihave just release Parampl
2.1.0:
https://github.com/arturolszak/parampl/releases/latest

The problem with renaming files is gone. Parampl should be now fully
compatible with Python 2 and 3.

Best regards.
Artur Olszak

**Comment by Jeffguitarhero** [comment]
Many thanks, the new version is working well.
